name: foss4g
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter-book
  - matplotlib
  - numpy
  - ghp-import
  - xarray
  - rioxarray
  - cftime
  - netcdf4
  - h5netcdf
  - cartopy
  - holoviews
  - hvplot
  - geopandas
  - pooch
  - pip
  - pip:
    - wget
    - sphinx-exercise
