name: foss4g
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyter-book
  - matplotlib
  - numpy
  - ghp-import
  - xarray
  - rioxarray
  - cftime
  - wget
  - netcdf4
  - h5netcdf
  - cartopy
  - holoviews
  - hvplot
  - geopandas
  - pip
  - pip:
    - sphinx-exercise
